version: 2
jobs:
  build:
    docker:
      - image: docker:git
        environment:
          GLIBC_VERSION: 2.24
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p artifacts
      - run: docker build --tag sgerrand/glibc-builder:$CIRCLE_SHA1 .
      - run: docker run --rm -e STDOUT=1 sgerrand/glibc-builder:$CIRCLE_SHA1 $GLIBC_VERSION /usr/glibc-compat > artifacts/glibc-bin-$GLIBC_VERSION-$(uname -m).tar.gz
      - persist_to_workspace:
          root: ~/docker-glibc-builder
          paths: artifacts
      - store_artifacts:
          path: artifacts
    working_directory: ~/docker-glibc-builder
  upload-master:
    docker:
      - image: golang:alpine
    steps:
      - run: apk add --no-cache git openssh-client
      - checkout
      - run: go get github.com/tcnksm/ghr
      - deploy:
          name: Upload to GitHub release
          command: ghr -u sgerrand --prerelease --delete unreleased artifacts
    working_directory: ~/docker-glibc-builder
  upload-tag:
    docker:
      - image: golang:alpine
    steps:
      - run: apk add --no-cache git openssh-client
      - checkout
      - run: go get github.com/tcnksm/ghr
      - deploy:
          name: Upload to GitHub release
          command: ghr -u sgerrand $CIRCLE_TAG artifacts/
    working_directory: ~/docker-glibc-builder
workflows:
  version: 2
  build-compile-upload:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - upload-master:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
          requires:
            - build
      - upload-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
